[package]
name = "datarowz"
version = "0.1.0"
edition = "2024"

[dependencies]
md5 = "0.8.0"
notify = "8.2.0"
rust-ini = "0.21.3"
sha1 = "0.10.6"
sha2 = "0.10.9"

[target.'cfg(windows)'.dependencies]
winreg = "0.50"
